import Head from "next/head";
import { useState, useEffect } from "react";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Header/Navbar";
import Inner_content from "../components/inner_content/Inner_content";
import Inner_Content_2 from "../components/inner_content_2/Inner_Content_2";
import Inner_vedio from "../components/inner_vedio/Inner_vedio";
import Leaderboard from "../components/Leaderboard/Leaderboard";
import Media from "../components/Media/Media";

export default function Home() {
  const [scrolH, setScrolH] = useState(true);

  useEffect(() => {
    let id = window.addEventListener("scroll", () => {
      setScrolH(window.scrollY < 50);
    });

    return () => {
      window.removeEventListener("scroll", id);
    };
  }, []);

  return (
    <div className="Main">
      <Head>
        <title>the movie db</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <>
        <Navbar scrolH={scrolH} />
        <Media />
        <Inner_content />
        <Inner_vedio />
        <Inner_Content_2 />
        <Leaderboard />
        <Footer />
      </>
    </div>
  );
}
