import Head from "next/head";
import React from "react";
import { useState, useEffect } from "react";
import Footer from "../components/Footer/Footer";
import Navbar from "../components/Header/Navbar";
import Info_page from "../components/info_page/Info_page";
import Media_tv from "../components/Media_Tv/Media_tv";
import Shortgar_bar from "../components/shortgar_bar/Shortgar_bar";

const Page_wrap = () => {
  const [scrolH, setScrolH] = useState(true);

  useEffect(() => {
    let id = window.addEventListener("scroll", () => {
      setScrolH(window.scrollY < 30);
    });

    return () => {
      window.removeEventListener("scroll", id);
    };
  }, []);
  return (
    <div>
      <Head>
        <title>Page wrap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <>
        <Navbar scrolH={scrolH} />
        <Shortgar_bar />
        <Info_page />
        <Media_tv />
        <Footer />
      </>
    </div>
  );
};

export default Page_wrap;
